{{ if .Values.fediblockhole.cron.sync.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fediblockhole.fullname" . }}-sync
  labels:
    {{- include "fediblockhole.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.fediblockhole.cron.sync.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "fediblockhole.fullname" . }}-sync
          {{- with .Values.jobAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ include "fediblockhole.fullname" . }}-sync
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - fediblock-sync
                - -c
                - "{{- include "fediblockhole.conf_file_path" . -}}{{- include "fediblockhole.conf_file_filename" . -}}"
              volumeMounts:
                - name: config
                  mountPath: {{ include "fediblockhole.conf_file_path" . | quote }}
                - name: allow
                  mountPath: {{ include "fediblockhole.allow_file_path" . | quote }}
                - name: block
                  mountPath: {{ include "fediblockhole.block_file_path" . | quote }}
          volumes:
            - name: config
              configMap:
                name: {{ include "fediblockhole.fullname" . }}-conf-toml
                items:
                - key: {{ include "fediblockhole.conf_file_filename" . | quote }}
                  path: {{ include "fediblockhole.conf_file_filename" . | quote }}
            - name: allow
              configMap:
                name: {{ include "fediblockhole.fullname" . }}-allow-csv
                items:
                - key: {{ include "fediblockhole.allow_file_filename" . | quote }}
                  path: {{ include "fediblockhole.allow_file_filename" . | quote }}
            - name: config
              configMap:
                name: {{ include "fediblockhole.fullname" . }}-block-csv
                items:
                - key: {{ include "fediblockhole.block_file_filename" . | quote }}
                  path: {{ include "fediblockhole.block_file_filename" . | quote }}
{{- end }}
